version: "3.9"
services:
  client:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./
        target: /home/node
      - type: volume
        target: /home/node/node_modules
  test:
    build: .
    volumes:
      - type: bind
        source: ./
        target: /home/node
      - type: volume
        target: /home/node/node_modules
    tty: true
    stdin_open: true
    command: ["npm", "run", "test"]
